async function seedTracks(prisma: any) {
  const tracks = [
    // SOFTWARE ENGINEERING
    {
      id: 'trk_python_fundamentals',
      domainId: 'dom_software',
      name: 'Python Fundamentals',
      slug: 'python-fundamentals',
      description: 'Core Python programming: variables, control flow, functions, OOP, and standard library essentials for robotics applications.',
      sortOrder: 1,
      startMonth: 1,
      endMonth: 3,
    },
    {
      id: 'trk_cpp_fundamentals',
      domainId: 'dom_software',
      name: 'C++ for Robotics',
      slug: 'cpp-for-robotics',
      description: 'C++ programming with focus on memory management, templates, and real-time systems needed for high-performance robotics code.',
      sortOrder: 2,
      startMonth: 3,
      endMonth: 6,
    },
    {
      id: 'trk_data_structures',
      domainId: 'dom_software',
      name: 'Data Structures & Algorithms',
      slug: 'data-structures-algorithms',
      description: 'Essential data structures and algorithms with robotics applications: graphs for path planning, trees for spatial indexing, and more.',
      sortOrder: 3,
      startMonth: 4,
      endMonth: 7,
    },
    {
      id: 'trk_software_architecture',
      domainId: 'dom_software',
      name: 'Software Architecture',
      slug: 'software-architecture',
      description: 'Design patterns, system architecture, testing, and CI/CD pipelines for production robotics software.',
      sortOrder: 4,
      startMonth: 7,
      endMonth: 10,
    },

    // ELECTRICAL ENGINEERING
    {
      id: 'trk_circuit_fundamentals',
      domainId: 'dom_electrical',
      name: 'Circuit Fundamentals',
      slug: 'circuit-fundamentals',
      description: 'DC and AC circuit analysis, Ohm\'s law, Kirchhoff\'s laws, and basic component behavior for robotics electronics.',
      sortOrder: 1,
      startMonth: 1,
      endMonth: 3,
    },
    {
      id: 'trk_embedded_systems',
      domainId: 'dom_electrical',
      name: 'Embedded Systems',
      slug: 'embedded-systems',
      description: 'Microcontroller programming, GPIO, I2C, SPI, UART protocols, and real-time embedded software for robot controllers.',
      sortOrder: 2,
      startMonth: 3,
      endMonth: 6,
    },
    {
      id: 'trk_sensors_actuators',
      domainId: 'dom_electrical',
      name: 'Sensors & Actuators',
      slug: 'sensors-actuators',
      description: 'Selection, interfacing, and signal conditioning for encoders, IMUs, LiDAR, cameras, motors, and servo systems.',
      sortOrder: 3,
      startMonth: 4,
      endMonth: 8,
    },

    // MECHANICAL ENGINEERING
    {
      id: 'trk_mechanics_fundamentals',
      domainId: 'dom_mechanical',
      name: 'Engineering Mechanics',
      slug: 'engineering-mechanics',
      description: 'Statics, dynamics, free body diagrams, and force analysis for understanding how robotic structures bear loads and move.',
      sortOrder: 1,
      startMonth: 1,
      endMonth: 3,
    },
    {
      id: 'trk_cad_design',
      domainId: 'dom_mechanical',
      name: 'CAD & 3D Printing',
      slug: 'cad-3d-printing',
      description: 'Computer-aided design using Fusion 360 and OnShape, plus additive manufacturing techniques for rapid prototyping.',
      sortOrder: 2,
      startMonth: 2,
      endMonth: 5,
    },
    {
      id: 'trk_mechanisms',
      domainId: 'dom_mechanical',
      name: 'Mechanisms & Transmissions',
      slug: 'mechanisms-transmissions',
      description: 'Gears, linkages, belt drives, lead screws, and power transmission systems used in robotic mechanisms.',
      sortOrder: 3,
      startMonth: 5,
      endMonth: 8,
    },

    // MACHINE LEARNING
    {
      id: 'trk_math_foundations',
      domainId: 'dom_ml',
      name: 'Math for ML',
      slug: 'math-for-ml',
      description: 'Linear algebra, calculus, probability, and statistics foundations required for understanding machine learning algorithms.',
      sortOrder: 1,
      startMonth: 1,
      endMonth: 4,
    },
    {
      id: 'trk_supervised_learning',
      domainId: 'dom_ml',
      name: 'Supervised Learning',
      slug: 'supervised-learning',
      description: 'Regression, classification, neural networks, and model evaluation techniques for robotics perception tasks.',
      sortOrder: 2,
      startMonth: 4,
      endMonth: 7,
    },
    {
      id: 'trk_computer_vision',
      domainId: 'dom_ml',
      name: 'Computer Vision',
      slug: 'computer-vision',
      description: 'Image processing, CNNs, object detection, segmentation, and depth estimation for robot perception.',
      sortOrder: 3,
      startMonth: 6,
      endMonth: 10,
    },
    {
      id: 'trk_deep_learning',
      domainId: 'dom_ml',
      name: 'Deep Learning',
      slug: 'deep-learning',
      description: 'Advanced neural network architectures including transformers, GANs, and self-supervised learning for robotics.',
      sortOrder: 4,
      startMonth: 8,
      endMonth: 12,
    },

    // REINFORCEMENT LEARNING
    {
      id: 'trk_rl_fundamentals',
      domainId: 'dom_rl',
      name: 'RL Fundamentals',
      slug: 'rl-fundamentals',
      description: 'Markov decision processes, value functions, Q-learning, and policy methods for training robot behaviors.',
      sortOrder: 1,
      startMonth: 5,
      endMonth: 8,
    },
    {
      id: 'trk_deep_rl',
      domainId: 'dom_rl',
      name: 'Deep Reinforcement Learning',
      slug: 'deep-rl',
      description: 'DQN, PPO, SAC, and actor-critic methods for complex robotic control and manipulation tasks.',
      sortOrder: 2,
      startMonth: 8,
      endMonth: 11,
    },
    {
      id: 'trk_sim_to_real',
      domainId: 'dom_rl',
      name: 'Sim-to-Real Transfer',
      slug: 'sim-to-real',
      description: 'Domain randomization, system identification, and transfer techniques to deploy simulation-trained policies on real robots.',
      sortOrder: 3,
      startMonth: 10,
      endMonth: 12,
    },

    // ROBOTICS SYSTEMS
    {
      id: 'trk_ros2_fundamentals',
      domainId: 'dom_robotics',
      name: 'ROS2 Fundamentals',
      slug: 'ros2-fundamentals',
      description: 'Robot Operating System 2: nodes, topics, services, actions, and launch systems for building modular robot software.',
      sortOrder: 1,
      startMonth: 2,
      endMonth: 5,
    },
    {
      id: 'trk_slam_navigation',
      domainId: 'dom_robotics',
      name: 'SLAM & Navigation',
      slug: 'slam-navigation',
      description: 'Simultaneous localization and mapping, path planning, obstacle avoidance, and autonomous navigation stacks.',
      sortOrder: 2,
      startMonth: 6,
      endMonth: 9,
    },
    {
      id: 'trk_manipulation',
      domainId: 'dom_robotics',
      name: 'Robot Manipulation',
      slug: 'robot-manipulation',
      description: 'Kinematics, dynamics, grasp planning, and motion planning for robotic arms and manipulation systems.',
      sortOrder: 3,
      startMonth: 7,
      endMonth: 11,
    },

    // CONTROL SYSTEMS
    {
      id: 'trk_classical_controls',
      domainId: 'dom_controls',
      name: 'Classical Control Theory',
      slug: 'classical-control-theory',
      description: 'PID control, transfer functions, stability analysis, Bode plots, and root locus methods for robot actuator control.',
      sortOrder: 1,
      startMonth: 2,
      endMonth: 5,
    },
    {
      id: 'trk_state_space',
      domainId: 'dom_controls',
      name: 'State Space Methods',
      slug: 'state-space-methods',
      description: 'State space representation, controllability, observability, pole placement, and Kalman filtering for robot state estimation.',
      sortOrder: 2,
      startMonth: 5,
      endMonth: 8,
    },
    {
      id: 'trk_optimal_control',
      domainId: 'dom_controls',
      name: 'Optimal & Adaptive Control',
      slug: 'optimal-adaptive-control',
      description: 'LQR, MPC, adaptive control, and trajectory optimization for advanced robotic motion control.',
      sortOrder: 3,
      startMonth: 9,
      endMonth: 12,
    },

    // SIMULATION
    {
      id: 'trk_gazebo',
      domainId: 'dom_simulation',
      name: 'Gazebo & URDF',
      slug: 'gazebo-urdf',
      description: 'Robot simulation with Gazebo: URDF/XACRO models, world creation, sensor plugins, and physics engines.',
      sortOrder: 1,
      startMonth: 3,
      endMonth: 6,
    },
    {
      id: 'trk_mujoco',
      domainId: 'dom_simulation',
      name: 'MuJoCo Simulation',
      slug: 'mujoco-simulation',
      description: 'High-fidelity physics simulation with MuJoCo for contact-rich manipulation, locomotion, and RL training environments.',
      sortOrder: 2,
      startMonth: 6,
      endMonth: 9,
    },
    {
      id: 'trk_isaac_sim',
      domainId: 'dom_simulation',
      name: 'NVIDIA Isaac Sim',
      slug: 'isaac-sim',
      description: 'GPU-accelerated simulation with Isaac Sim for large-scale RL training, synthetic data generation, and digital twins.',
      sortOrder: 3,
      startMonth: 9,
      endMonth: 12,
    },

    // FOUNDER THINKING
    {
      id: 'trk_founder_mindset',
      domainId: 'dom_founder',
      name: 'Founder Mindset',
      slug: 'founder-mindset',
      description: 'Develop the mental models, decision frameworks, and resilience needed to build a robotics startup from idea to product.',
      sortOrder: 1,
      startMonth: 1,
      endMonth: 6,
    },
    {
      id: 'trk_product_strategy',
      domainId: 'dom_founder',
      name: 'Product Strategy',
      slug: 'product-strategy',
      description: 'Market analysis, customer discovery, product-market fit, and go-to-market strategy for robotics products.',
      sortOrder: 2,
      startMonth: 4,
      endMonth: 9,
    },
    {
      id: 'trk_robotics_business',
      domainId: 'dom_founder',
      name: 'Robotics Business',
      slug: 'robotics-business',
      description: 'Fundraising, hardware economics, manufacturing scale-up, regulatory compliance, and building a robotics company.',
      sortOrder: 3,
      startMonth: 7,
      endMonth: 12,
    },
  ];

  for (const track of tracks) {
    await prisma.track.upsert({
      where: { slug: track.slug },
      update: track,
      create: track,
    });
  }

  console.log(`  ✓ Seeded ${tracks.length} tracks`);
}

module.exports = { seedTracks };
